### ISSUE TITLE
Add LICENSE file to the repository

### ISSUE THREAD

**Issue by bebatut** [bluenote-1577/sylph-utils#1]
Hello, 

I noticed that this repository currently doesn't have a LICENSE file. In order to clarify how others can use, distribute, and contribute to this project, could you please add a LICENSE file? A license would help ensure that the terms of usage are clear to everyone.

There are various open-source licenses to choose from, such as:

- [MIT License](https://choosealicense.com/licenses/mit/)
- [Apache 2.0 License](https://choosealicense.com/licenses/apache-2.0/)
- [GNU GPL v3](https://choosealicense.com/licenses/gpl-3.0/)

If you're unsure which license to pick, [choosealicense.com](https://choosealicense.com/) can guide you based on your preferences.

Thanks for considering this request!

**Comment by bluenote-1577** [comment]
Hi @bebatut 

I have added an MIT license to this repository. Sylph is also MIT licensed. Let mek now if that works for you.

Thanks!

**Comment by bebatut** [comment]
Perfect. Thanks a lot!
